/*
 * Copyright 2016 CUBRID Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/* Generated by dwoff - do not edit by hand */
#define OFF_PGBUF_NBUF         0
#define OFF_XCACHE_ENTRIES     440
#define OFF_XCACHE_USAGE       484
#define OFF_XCACHE_CLONE       488
#define OFF_QLIST_NPAGES       28
#define OFF_QPOOL_NENT         8
#define OFF_LK_NUMTRANS        0
#define OFF_LF_ALLOCCNT        12
#define OFF_LF_ALLOCCNT2       12
#define SZ_SESSION_STATE       312
#define SZ_CATALOG_ENTRY       48
#define SZ_FPCACHE_ENT         120
#define SZ_LK_TRAN_LOCK        152
#define SZ_CSS_CONN_ENTRY      480
#define SZ_VACUUM_DATA         184
#define OFF_PGBUF_BCBTAB       8
#define SZ_PGBUF_BCB           144
#define OFF_BCB_VPID           44
#define OFF_BCB_FLAGS          64
#define OFF_BCB_OLDEST_LSA     128
#define OFF_BCB_IOPAGE         136
#define OFF_IOBUF_IOPAGE       8
#define OFF_LOG_NXIO_LSA       48
#define OFF_LOG_APPEND_LSA     280
#define OFF_LOG_EOF_LSA        488
#define OFF_PSTAT_NVALS        0
#define OFF_PSTAT_GSTATS       8
#define OFF_PSTAT_INIT         44
#define SZ_PSTAT_METADATA      56
#define OFF_PSTATMD_PSID       0
#define OFF_PSTATMD_START      20
