#!/bin/sh
#
# Copyright 2016 CUBRID Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# gen-embedded.sh - offsets/*.tbl 을 C 헤더로 바꿔 바이너리에 내장한다.
#
# Usage: offsets/gen-embedded.sh [-o OUT.h] [DIR]
#   DIR     표가 있는 디렉터리 (기본: 이 스크립트가 있는 곳)
#   -o      출력 헤더 (기본: <src>/offsets_embedded.h)
#
# 왜 내장하는가
#   표가 파일로만 있으면 바이너리를 복사해 간 곳에 그 파일이 없고, 그러면 구버전
#   서버에서 방법 B 가 DWARF 추출이나 앵커 탐사로 내려간다. 표를 바이너리에 넣으면
#   **파일 하나로 모든 버전**을 본다.
#
#   표 전체가 약 5KB 라 바이너리 증가는 무시할 만하다.
#
# 내장해도 파일이 우선이다
#   --offsets 로 준 표가 내장 표보다 먼저 쓰인다. 새 패치 버전이 나왔을 때
#   바이너리를 다시 빌드하지 않고 표만 건네면 되기 때문이다.
#
# 표 텍스트를 그대로 넣는다
#   파싱은 파일 경로와 같은 함수(offs_text_load)를 쓴다. 숫자를 따로 뽑아 구조체
#   리터럴로 만들면 파일과 내장이 다르게 해석될 여지가 생긴다.
set -u

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
OUT="$HERE/../src/offsets_embedded.h"
DIR="$HERE"

while [ $# -gt 0 ]; do
    case "$1" in
        -o) OUT=$2; shift 2 ;;
        -h|--help) sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*) echo "unknown option: $1" >&2; exit 2 ;;
        *)  DIR=$1; shift ;;
    esac
done

n=$(ls "$DIR"/cubrid-*.tbl 2>/dev/null | wc -l)
[ "$n" -gt 0 ] || { echo "no cubrid-*.tbl in $DIR" >&2; exit 1; }

TMP="$OUT.tmp.$$"
{
    echo "/*"
    echo " * Copyright 2016 CUBRID Corporation"
    echo " *"
    echo " *  Licensed under the Apache License, Version 2.0 (the \"License\");"
    echo " *  you may not use this file except in compliance with the License."
    echo " *  You may obtain a copy of the License at"
    echo " *"
    echo " *      http://www.apache.org/licenses/LICENSE-2.0"
    echo " *"
    echo " *  Unless required by applicable law or agreed to in writing, software"
    echo " *  distributed under the License is distributed on an \"AS IS\" BASIS,"
    echo " *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."
    echo " *  See the License for the specific language governing permissions and"
    echo " *  limitations under the License."
    echo " */"
    echo "/* Generated by offsets/gen-embedded.sh - do not edit by hand."
    echo " * Source: offsets/cubrid-*.tbl  (regenerate after adding a table) */"
    echo "#ifndef CUB_TOP_OFFSETS_EMBEDDED_H"
    echo "#define CUB_TOP_OFFSETS_EMBEDDED_H"
    echo
    echo "typedef struct { const char *ver, *text; } embtbl_t;"
    echo "static const embtbl_t EMB_TBL[]={"
    for f in "$DIR"/cubrid-*.tbl; do
        ver=$(sed -n 's/^#meta version=\([0-9.]*\).*/\1/p' "$f" | head -1)
        [ -n "$ver" ] || ver=$(basename "$f" | sed 's/^cubrid-//;s/\.tbl$//')
        echo "  {\"$ver\","
        # 주석(#)과 빈 줄은 빼고 키=값 줄만 담는다 — 파서가 쓰는 것만 남긴다.
        grep -E '^[A-Z]' "$f" | sed 's/.*/    "&\\n"/'
        echo "  },"
    done
    echo "};"
    echo "#define EMB_TBL_N ((int)(sizeof EMB_TBL / sizeof EMB_TBL[0]))"
    echo
    echo "#endif"
} >"$TMP"

mv "$TMP" "$OUT"
echo "생성: $OUT  (표 $n 종, $(wc -c <"$OUT") bytes)"
